### ISSUE TITLE
Unable to access hystrix dashboard

### ISSUE THREAD

**Issue by weimeilin79** [jbossdemocentral/fuse-hystrix#1]
Tried using minishift, was unable to accss the dashboard using both URL links

http://hystrix-dashboard-fis-hystrix.192.168.99.100.xip.io/hystrix-dashboard/
http://hystrix-dashboard-fis-hystrix.192.168.99.100.xip.io/

Suspecting Permission denied error
```
Linking /maven/ROOT.war --> /opt/jetty/webapps/ROOT.war
ln: failed to create symbolic link '/opt/jetty/webapps/ROOT.war': Permission denied
Running Jetty: 
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL http://172.17.0.7:8778/jolokia/
2017-04-02 19:04:02.496:INFO:ifasjoejs.Server:jetty-8.y.z-SNAPSHOT
2017-04-02 19:04:02.555:INFO:ifasjoejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9779
2017-04-02 19:04:03.203:INFO::main: Logging initialized @1080ms
2017-04-02 19:04:03.281:WARN:oejs.HomeBaseWarning:main: This instance of Jetty is not running from a separate {jetty.base} directory, this is not recommended.  See documentation at http://www.eclipse.org/jetty/documentation/current/startup.html
2017-04-02 19:04:03.710:WARN:oejuc.FileNoticeLifeCycleListener:main: 
java.io.FileNotFoundException: /opt/jetty/jetty.state (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at java.io.FileWriter.<init>(FileWriter.java:78)
	at org.eclipse.jetty.util.component.FileNoticeLifeCycleListener.writeState(FileNoticeLifeCycleListener.java:45)
	at org.eclipse.jetty.util.component.FileNoticeLifeCycleListener.lifeCycleStarting(FileNoticeLifeCycleListener.java:57)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
	at org.eclipse.jetty.start.Main.start(Main.java:457)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
2017-04-02 19:04:03.725:INFO:oejs.Server:main: jetty-9.3.2.v20150730
2017-04-02 19:04:03.763:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/jetty-distribution-9.3.2.v20150730/webapps/] at interval 1
2017-04-02 19:04:03.827:INFO:oejs.ServerConnector:main: Started ServerConnector@63440df3{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2017-04-02 19:04:03.828:INFO:oejs.Server:main: Started @1705ms
2017-04-02 19:04:03.829:WARN:oejuc.FileNoticeLifeCycleListener:main: 
java.io.FileNotFoundException: /opt/jetty/jetty.state (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at java.io.FileWriter.<init>(FileWriter.java:78)
	at org.eclipse.jetty.util.component.FileNoticeLifeCycleListener.writeState(FileNoticeLifeCycleListener.java:45)
	at org.eclipse.jetty.util.component.FileNoticeLifeCycleListener.lifeCycleStarted(FileNoticeLifeCycleListener.java:62)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarted(AbstractLifeCycle.java:179)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
	at org.eclipse.jetty.start.Main.start(Main.java:457)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
```

**Comment by sabre1041** [comment]
Fixed in https://github.com/jbossdemocentral/fuse-hystrix/commit/1dc25921dbc00fc490f810cd5e1bb5ab1db595e6

@weimeilin79 Please retest with most up to date code base

**Comment by weimeilin79** [comment]
It worked!
